### ISSUE TITLE
Possibility to disable ssl even if defined(ssl)

### ISSUE THREAD

**Issue by inv2004** [mashingan/anonimongo#13]
Hello,
My application needs -d:ssl for websocket communication, but I found that anonimongo cannot connect to default mongo installation, because mongo is not configured for ssl

If I run without -d:ssl - everything works fine, but I cannot disable it for my app.

Question: Is it possible to disable ssl connection by some flag for newMongo?

Thank you,
  Alexander.

**Comment by inv2004** [comment]
https://github.com/mashingan/anonimongo/pull/14

**Comment by mashingan** [comment]
Anonimongo has support for ssl, you can also try to give the MongoUri url like `mongodb://domain:port/db?ssl=false` to disable it.
