### ISSUE TITLE
IOError from -d:ssl compiler flag

### ISSUE THREAD

**Issue by C-NERD** [mashingan/anonimongo#19]
Here is the part of the code that's causing the error
```nim
let mongo = newMongo[AsyncSocket](host = host, port = port)
mongo.noSlave()
if not waitFor mongo.connect():

    fatal(fmt"Failed to bind to mongodb on host {host} at port {port}")
    info("Quiting...")
    quit(QuitFailure)
```
To be specific it's `mongo.connect()`. It returns
```bash
streams.nim(412)         read
asyncfutures.nim(389)    read
utils.nim(40)            sendOpsIter
asyncfutures.nim(389)    read
asyncfutures.nim(389)    read
asyncfutures.nim(389)    read
asyncfutures.nim(389)    read
Error: unhandled exception: cannot read from stream [IOError]
```
when i compile with the -d:ssl compiler flag, I need the compiler flag because my application uses ssl for sending emails. Is there a way to fix this ?

**Comment by mashingan** [comment]
Is the mongod server running with option `--sslMode requireSSL` ?

**Comment by mashingan** [comment]
Or you can define when initialized Mongo like this `let mongo = newMongo[AsyncSocket](host = host, port = port, ssl = false)` or `let mongo = newMongo[AsyncSocket](MongoUri fmt"mongodb://{host}:{port}/")`

**Comment by C-NERD** [comment]
> Or you can define when initialized Mongo like this `let mongo = newMongo[AsyncSocket](host = host, port = port, ssl = false)` or `let mongo = newMongo[AsyncSocket](MongoUri fmt"mongodb://{host}:{port}/")`

This works. Thanks 👍

**Comment by mashingan** [comment]
The simple `newMongo` had issue with `when defined(ssl)` before, see issue #13 .  
Since this is solved, I'm going to close this one. If there's another problem, feel free to open new issue. Thanks
