### ISSUE TITLE
Possible issue with threads in 2.0 (?)

### ISSUE THREAD

**Issue by samsamros** [mashingan/anonimongo#27]
So, first off. It's great news that anonimongo is compiling in 2.0!
It's really exciting and as I begin to compile some applications to this, I notice the following warning that turned into a compile error:

```
.../.choosenim/toolchains/nim-2.0.0/lib/pure/asyncmacro.nim(292, 24) Warning: 'findOneNimAsyncContinue' is not GC-safe as it calls 'nameIterVar`gensym85' [GcUnsafe2]
.../questions_prompts.nim(293, 117) template/generic instantiation of `async` from here
.../.nimble/pkgs/anonimongo-0.7.0/anonimongo/collections.nim(108, 6) Warning: 'findOne' is not GC-safe as it calls 'findOneNimAsyncContinue' [GcUnsafe2]
.../questions_prompts.nim(293, 117) template/generic instantiation of `async` from here
```
I added the threadAnalysis off flag and that made it compile (this application does not use threads, so it does not have an issue). 
Another application that uses the update proc did not show this warning when compiled. 

I'm trying to figure out if this may be an error on my programing, as it was not intended to be threaded or if it may be related to anonimongo, and will produce issues for multi-threaded applications. 

Context:
* Nim 2.0, Anonimongo v0.7.0

* The mongo connection and authentication is done at the beginning of runtime, and then a loop starts querying an API. 

* The collection definition and findOne lives inside of an async proc. 
```
var 
  localcol = localdb["collection_name"]
...
var userVer = await localcol.findOne(bson({"field":parseInt(callbackData.data)}))
```
* This application does not require threading, so I turned off the analysis, and compiles well. I'm still testing it, but should run fine. 

* Compiled fine with threads on and orc in nim v1.6.*
-----

thing's I've tried:
* moving the collection definition outside the proc, does not work, and actually threw an error in 1.6.* when compiling with threads on and gc orc, which were meant to be defaults in 2.0, and was testing my applications possibilities of migrating code to 2.0. *This did not work*
* Switched findOne for update (just to test compile time errors, not for the actual application): 
```
.../.nimble/pkgs/anonimongo-0.7.0/anonimongo/collections.nim(149, 40) template/generic instantiation of `multisock` from here
.../.nimble/pkgs/anonimongo-0.7.0/anonimongo/collections.nim(148, 6) Error: 'update' is not GC-safe as it calls 'update'
```

- This runs without issues an another nim mini project I have which runs update on main as it traverses through massive csvs. It does not bring up this issue. Only inside an async proc.

This issue may not be pressing, and I may be doing it wrong :D as it was not intended to run with threads; however, I thought it may be a good idea to leave it here in case some other users encounter the problem!
Also, I will continue to test on my end!

**Comment by inv2004** [comment]
I can just confirm - I found that a lot of functions complain about gcsafe - decode , encode and etc

**Comment by inv2004** [comment]
@samsamros I marked some functions gcsafe for my code and Araq said it is ok. But I am not able to reproduce your examples.

You can check it in the draft https://github.com/mashingan/anonimongo/pull/28 or please provide runnable examples

**Comment by samsamros** [comment]
you're absolutely right! @inv2004 I'm working on a branch that includes what you've done, and several other procs inside anonimongo. I'll upload to a branch tomorrow if everything works :D 
Once your merge goes through, I'll rebase, but i've been adding gcsafe pragmas in several functions just for findOne(). I'm getting there, I can feel it!

**Comment by inv2004** [comment]
@samsamros any news on it? can I help somehow to merge it?

**Comment by samsamros** [comment]
@inv2004 I was thinking on sitting down this weekend to see if I could re-arrange the order of the procs and put them together to try the `{.push.}` pragma. I haven't seen any new issues with CRUD operations so far. I'm still testing. I've also been thinking that it may be a good idea to leave `{.gcsafe.}` to have a clear sense what procs may cause the compiler warning to go off, and also reduce our tinkering around with reordering the code. Also up to @mashingan on how to procede, but I think re-ordering the procs and testing the `{.push.}` pragma is worth a try.

**Comment by samsamros** [comment]
No new errors have arised since I've made these changes. Closing for now, but feel free to reopen!
