### ISSUE TITLE
Error: Cannot make async proc discardable. Futures have to be checked with `asyncCheck` instead of discarded

### ISSUE THREAD

**Issue by timotheecour** [mashingan/anonimongo#4]
same issue as https://github.com/SSPkrolik/nimongo/issues/88:

/Users/timothee/.nimble/pkgs/anonimongo-0.2.0/anonimongo/core/wire.nim(192, 60) Error: Cannot make async proc discardable. Futures have to be checked with `asyncCheck` instead of discarded

it happens since nim as of nim-lang/Nim#14176

**Comment by mashingan** [comment]
Several procs were defined in older version as pragma `async` and `discardable` could be passed together. But after I checked again, it shouldn't really `discardable`.
