### ISSUE TITLE
replicas silently ignored in mongodb://user:pass@host1:port1,host2:port2/

### ISSUE THREAD

**Issue by timotheecour** [mashingan/anonimongo#6]
`mongodb+srv` not working is reported in https://github.com/mashingan/anonimongo/issues/5; as a workaround, I'm trying to use the corresponding shards by explicitly listing the host/ports in the uri as follows:

```
mongodb+srv://user:pass@mongoatlas1.xxx.mongodb.net
=>
mongodb://user:pass@mongoatlas1-shard-00-00.xxx.mongodb.net:27017,mongoatlas1-shard-00-01.xxx.mongodb.net:27017,mongoatlas1-shard-00-02.xxx.mongodb.net:27017
```

however, this seems to silently only take into account the 1st host/port, so that if I do a write operation (eg `insert`), it fails with:
```
/Users/timothee/git_clone/nim/anonimongo/src/anonimongo/core/utils.nim(75) crudopsIter
Error: unhandled exception: not master [MongoError]
```

depending on the order I specify in the host/port list and depending on which of the replicas is the current master.

Given that we can't predict which replica is master (and that can change), this can be a problem.

## links
* see https://developer.mongodb.com/article/srv-connection-strings which explains a bit more the relationship between mongodb+srv and the replicas, and how to obtain the replicas from a srv host using a python script
* maybe related to this README:
> Cannot provide readPreference option because cannot support multihost URI connection.

**Comment by mashingan** [comment]
> see https://developer.mongodb.com/article/srv-connection-strings which explains a bit more the relationship between mongodb+srv and the replicas, and how to obtain the replicas from a srv host using a python script

Thanks, will look it later.

> maybe related to this README:

Exactly, as I didn't understand how the multihost played role so couldn't implement it. I've started adding the replica set commands (branch [replication-db](https://github.com/mashingan/anonimongo/tree/replication-db)) as I planned to add support for multihost URI connection.

> Error: unhandled exception: not master [MongoError]

This is related with multihost indeed. In [replication-db](https://github.com/mashingan/anonimongo/tree/replication-db) branch, I added the command `isMaster` so the Mongo object could check its connection whether it's master or not.  
Write operations can only be done on master connection while read operations is depend on `readPreferences`.

----
For implementing multi connections, the internal implementation will need to change to accommodate it.  
The current implementation only supports for single connection, it's just a matter of adding a layer above current implementation while keeping the consumed APIs (Mongodb commands) still the same.

**Comment by timotheecour** [comment]
@mashingan maybe this helps?
* docs https://docs.mongodb.com/manual/core/read-preference-mechanics/
* code: _mongoc_cmd_parts_assemble_mongos in src/libmongoc/src/mongoc/mongoc-cmd.c

(and as you probably already know, srv support in dnsclient.nim requires latest HEAD in https://github.com/ba0f3/dnsclient.nim/commit/bce86b18fa9a2dfecd781d55655a94b8b9c96daa; not yet in a tagged release)

**Comment by mashingan** [comment]
> docs https://docs.mongodb.com/manual/core/read-preference-mechanics/

I've currently reading from [server selection spec](https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection.rst) but this doc page also explains same.

> (and as you probably already know, srv support in dnsclient.nim requires latest HEAD in ba0f3/dnsclient.nim@bce86b1; not yet in a tagged release)

Yes, I've tried the seedlist lookup using dnsclient and it worked. I'm currently changing the internal Mongo object to accommodate multiple connections and to support `readPreferences` when selecting which server to read from.
Nimble can choose the github page and the latest HEAD by suffixing `@#head`
I installed the latest HEAD of dnsclient using that method.

**Comment by mashingan** [comment]
@timotheecour please try again with [fix-ssl-connections](https://github.com/mashingan/anonimongo/tree/fix-ssl-connections) as I've rebased this branch to [replicate-db](https://github.com/mashingan/anonimongo/tree/replication-db) branch.  
This also supports for multihost connections and I overloaded some of `newMongo` signature by its argument i.e:

```nim
let atlasuri = "mongodb+srv://user:pw@some-shard-cluster-domain.mongodb.com/test?ssl=true"
var mongo = newMongo(uri = atlasuri, poolconn = 2)

# the rest is same
```

`ReadPreferences` other than `ReadPreferences.primary` is still not supported and will throw error. By default the snipped above already set the `ReadPreferences` to `ReadPreferences.primary`.  
I'll gradually add other `ReadPreferences` for later.

**Comment by timotheecour** [comment]
thanks for the update, here's what I tried:
* connecting to atlas mongo version 4.4.0
* dnsclient.nim at HEAD bce86b18fa9a2dfecd781d55655a94b8b9c96daa
* anonimongo at HEAD of fix-ssl-connections 97d7abe83cf09d3275b30d087f4aada8617b2405
* `nim r -d:ssl main`
with:
```nim
when true:
  import anonimongo
  let uriserver = "mongodb+srv://user:pw@mongoatlas3.xxx.mongodb.net/admin?ssl=true"
  var mongo = newMongo(uri = uriserver, poolconn = 2)
```

gives:
`Error: unhandled exception: value out of range: 8027506285661089891 notin -2147483648 .. 2147483647 [RangeDefect]`

(see below for full context)

## note
when you throw (eg inside newMongo), using `raise newException` looses all the context of where it was thrown; if instead you do:
```nim
    except:
      raise newException(MongoError, &"Other error when sending query: {getCurrentExceptionMsg()}", e)
=>
    except Exception as e:
      raise e
```
then it shows the proper context; I'm getting:

```
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11095.nim(74) t11095
/Users/timothee/git_clone/nim/anonimongo/src/anonimongo/core/types.nim(297) newMongo
/Users/timothee/git_clone/nim/dnsclient.nim/src/dnsclient.nim(41) sendQuery
/Users/timothee/git_clone/nim/Nim_devel/lib/pure/net.nim(1559) sendTo
/Users/timothee/git_clone/nim/Nim_devel/lib/system/fatal.nim(49) sysFatal
[[reraised from:
/Users/timothee/git_clone/nim/timn/tests/nim/all/t11095.nim(74) t11095
/Users/timothee/git_clone/nim/anonimongo/src/anonimongo/core/types.nim(315) newMongo
]]
Error: unhandled exception: value out of range: 8027506285661089891 notin -2147483648 .. 2147483647 [RangeDefect]
```

**Comment by timotheecour** [comment]
yay! I'm fixing the above mentioned issue in https://github.com/ba0f3/dnsclient.nim/pull/2, after that, mongodb+srv seems to work!
still need to run more checks though, let's keep this issue open until it all works

what i don't understand is how you got it to work in your setup without https://github.com/ba0f3/dnsclient.nim/pull/2 ?

**Comment by mashingan** [comment]
> when you throw (eg inside newMongo), using raise newException looses all the context of where it was thrown;

Ah, yeah, I thought the stacktraces were appended to the new exception type.

> what i don't understand is how you got it to work in your setup without ba0f3/dnsclient.nim#2 ?
> which version of nim were you using?

I checked in Debian and Windows and both never threw that error.  
In my specific case, I did a bit different by adding the dnsserver argument to _"192.168.18.1"_ (ISP intranet dns server) because all other dns servers are failed. Hence I need to add the `dnsserver` argument in `newMongo` signature to solve that.

``nim -v``

```
Nim Compiler Version 1.2.0 [Windows: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

and

```
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

> still need to run more checks though, let's keep this issue open until it all works

Yeah, I need to add more guards to the passed multihost url too.

**Comment by timotheecour** [comment]
does it also work with  ba0f3/dnsclient.nim#2 ?

**Comment by mashingan** [comment]
Tried the patch and it worked no problem.

**Comment by timotheecour** [comment]
> Ah, yeah, I thought the stacktraces were appended to the new exception type.

I've reported it here: https://github.com/nim-lang/Nim/issues/15182

> Yeah, I need to add more guards to the passed multihost url too.

somehow mongo+srv works for certain mongo versions of mongo atlas clusters only:
works: Version 4.2.8,  4.4.0
doesn't work: 4.0.19, Version 3.6.19

is that your experience as well?

**Comment by mashingan** [comment]
> somehow mongo+srv seems to work for certain mongo versions of mongo atlas clusters only:
> works: Version 4.2.8, 4.4.0
> doesn't work: 4.0.19, Version 3.6.19

Could you copy and paste (or see) that particular version cluster logs? Unfortunately the free tier is locked to version 4.2.  
Or maybe just the error message from the snippet code.

I added support for all readPreferences except `nearest` and in my experience, when using other than `readPreferences.primary` it will need the connection to be set `slaveOk`.

> not a huge deal but this causes ambiguities in following case:
> var mongo = newMongo(uriserver, poolconn = 16)

Yes, I overloaded by string argument because I didn't want to change the existing single/direct connection which has string argument `host = localhost`.
I did differ between URI connection and direct string connection, but for multihost, couldn't rely on `uri.URI` type anymore.  
Thought of changing the function name like `newMongoUri`, or maybe adding a wrapper type like

```nim
type MultiHost* = object
    uri*: string

proc newMongo*(mhost: MultiHost ....): Mongo =
   # snip for the rest
```

Haven't decided which to pick, but for now it's overloaded argument, perhaps later if it's hard to differentiate and prone to be mistaken, I'll change to the wrapper type.

**Comment by mashingan** [comment]
As `fix-ssl-connections` is merged into `develop` branch, please pull and checkout to develop HEAD. After some few adjustment, especially the readme, I hope I'll be able to merge into `master` around next week.
